<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListerRepository extends EntityRepository
{
}
