<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PoliceAssuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliceAssuranceRepository extends EntityRepository
{
}
