<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifFlotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifFlotteRepository extends EntityRepository
{
}
