<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifGroupementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifGroupementRepository extends EntityRepository
{
}
