<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifAssuranceTemporaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifAssuranceTemporaireRepository extends EntityRepository
{
}
