<?php

namespace MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAssuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAssuranceRepository extends EntityRepository
{
}
